default:cacheblock cachemeasure speedcompare
cacheblock:cacheblock.c
	gcc cacheblock.c -o cacheblock -g
cachemeasure:cachemeasure.c
	gcc cachemeasure.c -o cachemeasure -g
speedcompare:speedcompare.c
	gcc speedcompare.c -o speedcompare -g
clean:
	@rm -rf cacheblock cachemeasure speedcompare
